import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../models/client.dart';

class PdfService {
  static Future<void> generateClientPdf(Client client) async {
    final font = await PdfGoogleFonts.interRegular();
    final boldFont = await PdfGoogleFonts.interBold();
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        theme: pw.ThemeData.withFont(base: font, bold: boldFont),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'CRM - Client Record',
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text('Date: ${client.date.toString().substring(0, 10)}'),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                'Client Details',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Divider(),
              _buildRow('Name:', client.name),
              _buildRow('AFM:', client.afm),
              _buildRow('Phone:', client.phone),
              _buildRow('Service Type:', client.serviceType),
              pw.SizedBox(height: 20),
              pw.Text(
                'Financial Summary',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Divider(),
              _buildRow('Total Amount:', '${client.total}€'),
              _buildRow('Paid Amount:', '${client.paid}€'),
              _buildRow(
                'Outstanding Balance:',
                '${client.balance}€',
                isBold: true,
              ),
              pw.SizedBox(height: 40),
              pw.Text(
                'Notes:',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(client.requestNotes.isEmpty ? '-' : client.requestNotes),
              pw.Spacer(),
              pw.Footer(trailing: pw.Text('Generated by Client Manager v2')),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  static pw.Widget _buildRow(
    String label,
    String value, {
    bool isBold = false,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(
              label,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Text(
            value,
            style: isBold ? pw.TextStyle(fontWeight: pw.FontWeight.bold) : null,
          ),
        ],
      ),
    );
  }

  static Future<Uint8List> generateClientListPdf(
      List<Client> clients, String savePath) async {
    final font = await PdfGoogleFonts.interRegular();
    final boldFont = await PdfGoogleFonts.interBold();
    final pdf = pw.Document();

    // Define table headers
    final headers = [
      'ID',
      'Όνομα',
      'Τηλέφωνο',
      'Υπηρεσία',
      'ΑΦΜ',
      'ΑΜΚΑ',
      'Taxisnet',
      'Κλειδάριθμος',
      'Κατάσταση',
      'Υπόλοιπο'
    ];

    // Convert client data to table rows
    final data = clients
        .map((c) => [
              c.id.toString(),
              c.name,
              c.phone,
              c.serviceType,
              c.afm,
              c.amka.isNotEmpty ? c.amka : '-',
              c.hasTaxisnet ? 'Ναι' : 'Όχι',
              c.kleidarithmos.isNotEmpty ? c.kleidarithmos : '-',
              c.customerStatus,
              '${c.balance.toStringAsFixed(2)}€',
            ])
        .toList();

    pdf.addPage(
      pw.MultiPage(
        pageFormat:
            PdfPageFormat.a4.landscape, // Use landscape for wider tables
        theme: pw.ThemeData.withFont(base: font, bold: boldFont),
        header: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Πελατολόγιο CRM',
                style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue800),
              ),
              pw.SizedBox(height: 5),
              pw.Text(
                'Ημερομηνία εξαγωγής: ${DateTime.now().toIso8601String().substring(0, 10)}',
                style:
                    const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
              ),
              pw.SizedBox(height: 20),
            ]),
        build: (context) {
          return [
            pw.TableHelper.fromTextArray(
              headers: headers,
              data: data,
              border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
              headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration:
                  const pw.BoxDecoration(color: PdfColors.blueGrey800),
              rowDecoration: const pw.BoxDecoration(
                  border: pw.Border(
                      bottom:
                          pw.BorderSide(color: PdfColors.grey300, width: 0.5))),
              cellAlignment: pw.Alignment.centerLeft,
              cellPadding: const pw.EdgeInsets.all(5),
              cellStyle: const pw.TextStyle(fontSize: 10),
              oddRowDecoration:
                  const pw.BoxDecoration(color: PdfColors.grey100),
            )
          ];
        },
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 10),
          child: pw.Text(
            'Σελίδα ${context.pageNumber} από ${context.pagesCount}',
            style: const pw.TextStyle(color: PdfColors.grey),
          ),
        ),
      ),
    );

    // Save the PDF to the specified path
    // We are no longer using Printing.layoutPdf() to avoid immediately popping up the print dialog
    // when we just want to save it as an export.
    // We'll return the bytes so the caller can save it.
    final bytes = await pdf.save();
    return bytes;
  }
}
